config/routes.rb
Rails.application.routes.draw do
  resources :stories
  resources :users
  resources :sessions

  get '/signup', to: 'users#new'
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/stories/new', to:'stories#new'


  root 'stories#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :logined!, :current_user, :hinted_text_field_tag, :hinted_password_field_tag

  def logined!
    !!current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def require_login
    unless logined!
      redirect_to login_path
    end
  end

  def hinted_text_field_tag(name, value = nil, hint = "Click and enter text", options={})
    value = value.nil? ? hint : value
    text_field_tag name, value, {:onclick => "if($(this).value == '#{hint}'){$(this).value = ''}", :onblur => "if($(this).value == ''){$(this).value = '#{hint}'}" }.update(options.stringify_keys)
  end

  def hinted_password_field_tag(name, value = nil, hint = "Click and enter text", options={})
  value = value.nil? ? hint : value
  password_field_tag name, value, {:onclick => "if($(this).value == '#{hint}'){$(this).value = ''}", :onblur => "if($(this).value == ''){$(this).value = '#{hint}'}" }.update(options.stringify_keys)
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(nickname: params[:nickname])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to stories_path
    else
      flash[:error] = "用户名与密码不匹配"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :require_login

  def index
    @stories = current_user.stories
    @story = Story.new
  end

  def new
    @story = Story.new
  end

  def create
    story = Story.new(story_params)
    story.attributes = story_params.merge!(user_id: current_user.id)
    if story.save
      redirect_to stories_path
    else
      Rails.logger.debug "---------- #{story.errors.inspect}"
      render :new
    end
  end

  def edit
    @story = Story.find params[:id]
  end

  def show
    @story = Story.find params[:id]
  end

  def update
    story = Story.find params[:id]
    if story.update(story_params)
      redirect_to stories_path
    else
      render :index
    end
  end

  def destroy
    story = Story.find params[:id]
    story.destroy  # delete 和 destroy 有什么区别？
    redirect_to stories_path
  end

  private
  def story_params
    params.require(:story).permit(:title, :body, :avatar)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to stories_path
    else
      render :new
    end
  end

  private
  def user_params
    params[:user].permit(:nickname, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>MyStory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <div class="header">
      <%= image_tag "pen.png", class: "log" %><span class="title">我的故事</span>
      <div class="user_info">
        <% if logined! %>
          <span class="username"><%= current_user.nickname %></span><%= link_to "退出", logout_path, method: :delete %>
        <% end %>
      </div>
    </div>

    <%= yield %>

    <div class="footer">
    @洋芋
    </div> <!-- footer end -->

  </body>

</html>

app/views/stories/_form.html.erb
<div class="form_wrapper">
  <%= form_for @story do |f| %>
    <div class="form_item">
      <label>故事图片</label><br/>
      <%= f.file_field :avatar %>
    </div>
    <div class="form_item">
      <label>故事标题</label><br/>
      <%= f.text_field :title, class: 'long-txt' %>
    </div>
    <div class="form_item">
      <label>故事正文</label><br/>
      <%= f.text_area :body, :class => "tinymce", :rows => 14, :cols => 120 %>
      <%= tinymce %>
    </div>
    <div class="btn">
      <%= f.submit "提交", class: 'btn_submit' %>
      <%= link_to "取消", stories_path, class: 'btn_cancel' %>
    </div>
  <% end %>
</div>

app/views/stories/edit.html.erb
<div class="nav">
  <%= link_to "首页", stories_path %><small class="arrow">></small><span class="trace">修改故事</span>
</div>

<div class="page">
  <%= render 'stories/form' %>
</div>

app/views/stories/index.html.erb
<div class="page">
  <%= link_to "写故事", new_story_path, class: 'btn_create' %><br/>
  <% @stories.each do |story| %>
  <div class="story_wrapper">
    <div class="pic_wrapper">
      <%= link_to image_tag(story.avatar_url(:small_thumb).to_s), story_path(story.id) %>
    </div>
    <div class="story_title">
      <%= link_to story.title, story_path(story.id) %>
    </div>
    <div class="story_info">
      <div class="timeinfo">
        <%= story.created_at.to_formatted_s(:db) %>
      </div>
      <div class="operation">
        <%= link_to "编辑", edit_story_path(story.id) %>
        <%= link_to "删除", story_path(story.id), method: :delete %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/stories/new.html.erb
<div class="nav">
  <%= link_to "首页", stories_path %><small class="arrow">></small><span class="trace">写故事</span> 
</div>

<div class="page">
  <%= render 'stories/form' %>
</div>

app/views/stories/show.html.erb
<div class="nav">
  <%= link_to "首页", stories_path %><small class="arrow">></small>
  <span class="trace"><%= @story.title %></span>
</div>

<div class="page">
  <div class="form_wrapper">
    <div class="big_pic">
      <%= image_tag (@story.avatar_url(:thumb).to_s) %>
    </div>
    <h3><%= @story.title %></h3>
    <p class="timeinfo1"><%= @story.created_at.to_formatted_s %></p>
    <div class="body_contain">
      <%= sanitize(@story.body) %>
    </div>
  </div>

</div>

app/views/users/new.html.erb
<div class="box">
  <h2>注册</h2>
  <% if flash[:error] %>
  <div class="error"><%= flash[:error] %></div>
  <% end %>
  <div class="account">
    <%= form_for @user do |f| %>
      <div class="form_item">
        <%= f.text_field :nickname, placeholder: "用户名" %>
      </div>
      <div class="form_item">
        <%= f.password_field :password, placeholder: "密码" %>
      </div>
      <p><%= f.submit "注册", class: 'btn_submit' %></p>
    <% end %>
    <p><%= link_to "登录", login_path %></p>
  </div>
</div>